### ISSUE TITLE
About image features

### ISSUE THREAD

**Issue by JXZe** [batra-mlp-lab/visdial-challenge-starter-pytorch#15] opened 2019-05-27 16:47 UTC
Hello! Thank you for providing the features of the image. However I didn't find the information of boxes of these features. Can you provide the image features with the information of boxes? Thanks a lot.

**Comment by kdexd** [comment] 2019-05-29 15:59
Hi @JXZe ,

Traditionally the bottom-up top-down attention used in LF encoder does not require the bounding box coordinates of region proposals, hence for keeping the file size minimal, we did not provide the bounding box coordinates. You can set up [detectron](https://www.github.com/facebookresearch/detectron) in a docker container as outlined in README and use the feature extraction script (`data/extract_features_detectron.py`) to extract the boxes, object classes and confidence scores of region proposals.

**Comment by JXZe** [comment] 2019-05-31 14:21
Thank you ! And  I want to know if I don't have GPU on my computer , will I set up detectron successfully？

**Comment by kdexd** [comment] 2019-05-31 15:31
Yes, it seems like Detectron supports CPU-only execution (although inference will be much slower as compared to GPU mode).

**Comment by JXZe** [comment] 2019-06-02 16:26
hello!

I can't understand the meaning of this command line:

nvidia-docker run -u $（ id -u ）：$（ id -g ） \

(id -u ) (id -g) what are they meant for? What should I replace them in my command line ?

Thanks a lot!

**Comment by kdexd** [comment] 2019-06-02 19:15
This sets your username and group (of your base OS) inside the docker environment. This would help to edit/execute any files inside the docker environment as the root inside docker environment may not have write/execute permissions.

**Comment by JXZe** [comment] 2019-06-03 14:13
When I set the Docker under your instructions in README,I run the command :

docker run -u 501:20 -v $PROJECT_ROOT:/workspace --shm-size 12G visdialch python data/extract_features_detectron.py   

However I got the erro like this:

from detectron.core.config import assert_and_infer_cfg, merge_cfg_from_file
ModuleNotFoundError: No module named 'detectron'

It means I set the Docker wrong?

**Comment by kdexd** [comment] 2019-06-03 19:33
It looks like your docker container either did not build successfully -- could you post the output of docker build command?

**Comment by JXZe** [comment] 2019-06-04 15:37
The output of docker build command:

Removing intermediate container 80f036380096
 ---> e7fb80da1c03
Step 9/9 : WORKDIR /workspace
 ---> Running in 6728a5901d86
Removing intermediate container 6728a5901d86
 ---> 2c0159307723
Successfully built 2c0159307723
Successfully tagged visdialch:latest

Maybe I didn't install nvidia-docker ？(I only install docker because I don't have GPU)

**Comment by JXZe** [comment] 2019-06-07 15:36
Hello: 

 I am very happy that I extract the boxes, object classes and confidence scores of region proposals successfully  ! ! Thank you very much ! ! 

However, I still have some questions to ask you. 

1 . I see many models in [Detectron Model Zoo and Baselines](https://github.com/facebookresearch/Detectron/blob/master/MODEL_ZOO.md) and many configs in [there ](https://github.com/facebookresearch/Detectron/tree/master/configs/12_2017_baselines). And I want to know which model you are using because I want to be consistent with you. 

2.For test , I choose a model in Detectron Model Zoo and Baselines/End-to-End Faster & Mask R-CNN Baselines/X-101-64x4d-FPN . However , dimension of each image proposals of this model is 1024. I see the dimension of your  image proposals  is 2048 . Therefore , it's very important for me to know which model do you choose.

And I find if have no GPU, we couldn’t extract image features successfully for the code in Detectron need GPU!

Thanks a lot !

**Comment by quanguet** [comment] 2019-07-28 01:04
Yeah, most of the pretrained models only yield 1024-dim. It would be really helpful if you give us the exact model from Detectron to get the same dimension 2048 for a fair comparison.
Many thanks.

**Comment by kdexd** [comment] 2019-07-29 02:58
We have a model trained using Visual Genome dataset, similar configuration as https://www.github.com/peteanderson80/bottom-up-attention. Unfortunately, we do not own that detector and hence are not permitted to release it. All we have are features. You could alternatively set ^this repo up (it's in Caffe) and use that detector / train a similar one.

**Comment by quanguet** [comment] 2019-07-31 01:40
Thank you a lot. I've already reproduced the features. I think you can close this issue.

**Closed** 2019-08-04 07:14 UTC

**Comment by quanguet** [comment] 2019-08-08 13:25
Sorry for open this again. I found that when I use the extracted features (36 features per image) provided by @peteanderson,  it yields lower accuracy on Visdial than the features that you extracted. These features provided by @peteanderson can be generated by using the default configuration and his pretrained model. I expected that these features should be the same as yours but actually they are not. 
![image](https://user-images.githubusercontent.com/30741785/62706328-3d383f80-ba2a-11e9-9ee5-3a70601b9f5f.png)
Could you share some insight which is  super helpful for us to reproduce the result <3 
1. Did you use the default configuration as below? Or did you change some values?
![image](https://user-images.githubusercontent.com/30741785/62706915-65746e00-ba2b-11e9-808a-69816b71c260.png)

2. Which pretrained model did you use? `the pretrained model` or `the alternative pretrained model`:
![image](https://user-images.githubusercontent.com/30741785/62706798-2fcf8500-ba2b-11e9-8000-d988622434c1.png)
Many thanks beforehand.
